In [110]:
import numpy as np

## 1. How do you create a NumPy array from a list?

In [111]:
lst1=[1,2,3,4,5,6,78,9,5]


In [112]:
arr=np.array(lst1)
print(arr)

[ 1  2  3  4  5  6 78  9  5]


## 2. What is the difference between np.array() and np.asarray()?


In [113]:
arr=np.array(lst1)
print(arr)

[ 1  2  3  4  5  6 78  9  5]


In [114]:
asarr=np.asarray(lst1)
print(asarr)

[ 1  2  3  4  5  6 78  9  5]


## 3. How do you create a multidimensional array in NumPy?


In [115]:
multi_arr=np.array([
    [1,2,3,4,5,6,9],
    [4,5,6,78,9,7,8],
    [12,35,65,98,65,87,45]
])

In [116]:
multi_arr.ndim

2

In [117]:
multi_arr.shape

(3, 7)

## 4. What is the shape of a NumPy array?


In [118]:
multi_arr.shape

(3, 7)

## 5. How do you access elements in a NumPy array?


In [119]:
multi_arr[2][5]

np.int64(87)

## 6. How do you slice a NumPy array?


In [120]:
multi_arr[0::]


array([[ 1,  2,  3,  4,  5,  6,  9],
       [ 4,  5,  6, 78,  9,  7,  8],
       [12, 35, 65, 98, 65, 87, 45]])

In [121]:
multi_arr[1::]

array([[ 4,  5,  6, 78,  9,  7,  8],
       [12, 35, 65, 98, 65, 87, 45]])

In [122]:
multi_arr[::-1]

array([[12, 35, 65, 98, 65, 87, 45],
       [ 4,  5,  6, 78,  9,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  9]])

## 7. What is the difference between indexing and slicing in NumPy?


In [123]:
# indixing 
arr=np.arange(0,32,2)
arr=arr.reshape(4,4)
print(arr)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


In [124]:
arr[1][2]

np.int64(12)

In [125]:
# slicing
arr[1:]

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

## 8. How do you perform basic arithmetic operations on NumPy arrays?


In [126]:
print("First array")
arr1=np.arange(0,20,2)
arr1=arr1.reshape(10)
arr1

First array


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [127]:
print("Second array")
arr2=np.arange(0,30,3)
arr2=arr2.reshape(10)
print(arr2)

Second array
[ 0  3  6  9 12 15 18 21 24 27]


In [128]:
# addition
print(np.add(arr1,arr2))

# substract
print("\n")
print("Substraction")
print(np.subtract(arr1,arr2))

# multiply
print("\n")
print("Multiplication")
print(np.multiply(arr1,arr2))

# divide
print("\n")
print("Division")
print(np.divide(arr1,arr2))

[ 0  5 10 15 20 25 30 35 40 45]


Substraction
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


Multiplication
[  0   6  24  54  96 150 216 294 384 486]


Division
[       nan 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667
 0.66666667 0.66666667 0.66666667 0.66666667]


C:\Users\omkar\AppData\Local\Temp\ipykernel_6412\3538551885.py:17: RuntimeWarning: invalid value encountered in divide
  print(np.divide(arr1,arr2))


## 9. How do you perform element-wise operations on NumPy arrays?


In [129]:
print(arr1)
print(arr2)

add=np.add(arr1,arr2)
print("element vise addition:-",add)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]
element vise addition:- [ 0  5 10 15 20 25 30 35 40 45]


In [130]:
# substraction 
print("first array:-",arr1)
print("\n")

print("Second array:-",arr2)
print("\n")
add=np.subtract(arr1,arr2)
print("element wise substraction:-",add)


first array:- [ 0  2  4  6  8 10 12 14 16 18]


Second array:- [ 0  3  6  9 12 15 18 21 24 27]


element wise substraction:- [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [131]:
# multiplication

print("first array:-",arr1)
print("\n")

print("Second array:-",arr2)
print("\n")
add=np.multiply(arr1,arr2)
print("element wise substraction:-",add)


first array:- [ 0  2  4  6  8 10 12 14 16 18]


Second array:- [ 0  3  6  9 12 15 18 21 24 27]


element wise substraction:- [  0   6  24  54  96 150 216 294 384 486]


In [132]:
# division 

print("first array:-",arr1)
print("\n")

print("Second array:-",arr2)
print("\n")
add=np.divide(arr1,arr2)
print("element wise division:-",add)


first array:- [ 0  2  4  6  8 10 12 14 16 18]


Second array:- [ 0  3  6  9 12 15 18 21 24 27]


element wise division:- [       nan 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667
 0.66666667 0.66666667 0.66666667 0.66666667]


C:\Users\omkar\AppData\Local\Temp\ipykernel_6412\719214870.py:8: RuntimeWarning: invalid value encountered in divide
  add=np.divide(arr1,arr2)


## 10. What is broadcasting in NumPy?

In [133]:
arr1=np.array([1,2,3,56,48])

print(arr1*2)


[  2   4   6 112  96]


## 13. How do you create a NumPy array with a specific data type?


In [134]:
# creation of string array
arr=np.array([1,2,3,6,5,5],dtype=str)
print(arr)
print("\n")

# creation of complex datatype array?\
arr1=np.array([1,5,6,8,9,],dtype=complex)
print(arr1)

['1' '2' '3' '6' '5' '5']


[1.+0.j 5.+0.j 6.+0.j 8.+0.j 9.+0.j]


## 14. What is the difference between np.int32 and np.int64?


In [135]:
arr=np.array([1.0,2.5,23.5],dtype='int32')
print(arr)
print(arr.dtype)
print("\n")
arr=np.array([1.0,2.5,23.5],dtype='int64')
print(arr)
print(arr.dtype)

[ 1  2 23]
int32


[ 1  2 23]
int64


## 15. How do you convert a NumPy array to a Python list?


In [136]:
arr=np.random.randint(0,45,size=5)
print(arr)
print(type(arr))
print("\n")
lst=list(arr)
print(lst)
print(type(lst))

[21 16 30 38  5]
<class 'numpy.ndarray'>


[np.int32(21), np.int32(16), np.int32(30), np.int32(38), np.int32(5)]
<class 'list'>


 ## How do you use np.unique() to get unique elements in an array?


In [137]:
arr=np.random.randint(0,95,size=20)
print(arr)
print("\n")
arr1=np.array([1,2,3,5,6,4,8,9,9,5,5,6,3,3,3,2,2,4,4,10])
print(np.unique(arr1))

[87 15 17 40 42 18 90  5 46 51 12 50 16 20 72 78 13  3 33 19]


[ 1  2  3  4  5  6  8  9 10]


 ## How do you use np.sort() to sort an array?

 

In [138]:
arr=np.random.randint(0,56,size=15)
print("This is unsorted array",arr)

print("This is sorted array:-",np.sort(arr))


This is unsorted array [14 10 55 16 38 44 30 12 19 55 44 42 14 48 25]
This is sorted array:- [10 12 14 14 16 19 25 30 38 42 44 44 48 55 55]


##  How do you use np.all() to check if all elements in an array are true?

In [139]:
print(arr)
print(np.all(a=arr))

[14 10 55 16 38 44 30 12 19 55 44 42 14 48 25]
True


## How do you use np.where() to create a conditional array?

In [140]:
arr=np.random.randint(0,56,size=20)
print("This is orignal array:-",arr)



This is orignal array:- [26 50 29 40  7 12  5  5 52 33 49 21 19 49  7 19 47 21 30 43]


## How do you create a NumPy array with random values?
 
 

In [143]:
arr=np.random.randint(0,20,size=5)
print(arr)

[ 0 12 13  5 12]


## How do you use np.random.rand() to create an array with random values?



In [147]:
arr=np.random.rand()
print(arr)

0.67969296241276


##  How do you use np.random.normal() to create an array with random values?

In [149]:
arr=np.random.normal()
print(arr)

-0.4240371209445219


17. What is the purpose of np.reshape()?
18. How do you use np.reshape() to change the shape of an array?
19. What is the purpose of np.transpose()?
20. How do you use np.transpose() to swap axes in an array?
21. What is the purpose of np.swapaxes()?
22. How do you use np.swapaxes() to swap axes in an array?
23. What is the purpose of np.flatten()?
24. How do you use np.flatten() to flatten an array?
25. What is the purpose of np.ravel()?
26. How do you use np.ravel() to flatten an array?
27. What is the difference between np.flatten() and np.ravel()?